import { useEffect, useState } from 'react';
import type { User } from 'firebase/auth';
import { signInWithEmailAndPassword, signOut } from 'firebase/auth';
import { fieldOpsApi, type Dashboard, type Site } from './api';
import { auth } from './firebase';

type Props = { user: User };
const timeAgo = (iso?: string | null) => { if (!iso) return 'No reading'; const minutes = Math.max(0, Math.round((Date.now() - new Date(iso).getTime()) / 60000)); return minutes < 60 ? `${minutes}m ago` : `${Math.floor(minutes / 60)}h ${minutes % 60}m ago`; };

export function Login() {
  const [error, setError] = useState('');
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await signInWithEmailAndPassword(auth, String(form.get('email')).trim(), String(form.get('password'))); } catch { setError('Unable to sign in with that administrator account.'); } }
  return <main className="login-shell"><form className="login-card" onSubmit={submit}><div className="mark">FO</div><p className="eyebrow">FIELDOPS</p><h1>Operations dashboard</h1><p>Use your administrator account to view live site status.</p><label>EMAIL<input required name="email" type="email" autoComplete="email" /></label><label>PASSWORD<input required name="password" type="password" autoComplete="current-password" /></label>{error && <p className="error">{error}</p>}<button type="submit">Sign in</button></form></main>;
}

function AlertList({ dashboard }: { dashboard: Dashboard }) { return <article className="card alerts"><div className="card-heading"><h2>Needs attention</h2><span>{dashboard.alerts.length} alerts</span></div><ul>{dashboard.alerts.length ? dashboard.alerts.map(alert => <li className={`alert ${alert.severity}`} key={`${alert.type}-${alert.resourceId}`}><b>{alert.resourceName}</b><span>{alert.message}</span></li>) : <li className="all-clear">All readings are current.</li>}</ul></article>; }
function ActiveWells({ dashboard }: { dashboard: Dashboard }) { return <article className="card"><div className="card-heading"><h2>Active wells</h2><span>{dashboard.activeWells.length} online</span></div>{dashboard.activeWells.length ? <ul>{dashboard.activeWells.map(well => <li key={well.id} style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '14px 18px', borderTop: '1px solid #ececec' }}><span style={{ color: well.color, fontSize: 20 }} aria-hidden="true">●</span><div><b>{well.name}</b><small>{well.plannedStages} planned stages</small></div></li>)}</ul> : <p className="empty">No active wells at this location.</p>}</article>; }
function TrailerTable({ dashboard }: { dashboard: Dashboard }) { return <article className="card"><div className="card-heading"><h2>Trailer readings</h2><span>Location-wide</span></div>{dashboard.trailers.length ? <table><thead><tr><th>Trailer</th><th>Pressure</th><th>Temp</th><th>Last reading</th></tr></thead><tbody>{dashboard.trailers.map(trailer => <tr key={trailer.id}><td><b>{trailer.trailerNumber}</b><small>Position {trailer.position}</small></td><td>{trailer.latestReading ? `${trailer.latestReading.pressurePsi.toLocaleString()} PSI` : '—'}</td><td>{trailer.latestReading?.temperatureF == null ? '—' : `${trailer.latestReading.temperatureF} °F`}</td><td>{timeAgo(trailer.latestReading?.recordedAtIso)}</td></tr>)}</tbody></table> : <p className="empty">No active trailers.</p>}</article>; }
function InventoryTable({ dashboard }: { dashboard: Dashboard }) { const { inventory } = dashboard; return <article className="card"><div className="card-heading"><h2>Container inventory</h2><span>{inventory.containers.length} containers · Low ISO threshold {inventory.lowIsoThresholdInches} in</span></div>{inventory.containers.length ? <table><thead><tr><th>Container</th><th>Type</th><th>Strap</th><th>Updated</th></tr></thead><tbody>{inventory.containers.map(container => <tr key={container.id}><td><b>{container.name}</b><small>{container.chemical} · {container.area}</small></td><td>{container.type}</td><td>{container.strap == null ? '—' : `${container.strap} in`}</td><td>{timeAgo(container.updatedAtIso)}</td></tr>)}</tbody></table> : <p className="empty">No containers at this location.</p>}</article>; }

export function App({ user }: Props) {
  const [sites, setSites] = useState<Site[]>([]); const [siteId, setSiteId] = useState(''); const [dashboard, setDashboard] = useState<Dashboard>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [refreshKey, setRefreshKey] = useState(0);
  useEffect(() => { fieldOpsApi.listSites(user).then(foundSites => { setSites(foundSites); if (foundSites.length === 1) setSiteId(foundSites[0].id); }).catch(reason => setError(reason.message)); }, [user]);
  useEffect(() => { if (!siteId) return; setLoading(true); setError(''); fieldOpsApi.dashboard(user, siteId).then(setDashboard).catch(reason => setError(reason.message)).finally(() => setLoading(false)); }, [siteId, user, refreshKey]);
  const lowIsos = dashboard?.inventory.alerts.filter(alert => alert.type === 'low-iso').length ?? 0;
  return <><header><div className="brand"><span>FO</span><strong>FieldOps</strong><small>Operations dashboard</small></div><div className="actions"><button className="secondary" disabled={!siteId || loading} onClick={() => setRefreshKey(key => key + 1)}>Refresh</button><button className="link" onClick={() => signOut(auth)}>Sign out</button></div></header><main className="page"><section className="heading"><div><p className="eyebrow">LIVE OPERATIONS</p><h1>Dashboard</h1><p className="muted">{dashboard ? `Updated ${new Date(dashboard.generatedAtIso).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}` : 'Select a location to load its current status.'}</p></div><label className="site-picker">LOCATION<select value={siteId} onChange={event => setSiteId(event.target.value)}><option value="">Choose a location</option>{sites.map(site => <option value={site.id} key={site.id}>{site.name}</option>)}</select></label></section>{error ? <p className="empty">{error}</p> : loading ? <p className="empty">Loading live site data…</p> : dashboard ? <><section className="metrics"><article><small>ACTIVE TRAILERS</small><strong>{dashboard.trailers.length}</strong></article><article><small>LOW ISO TANKS</small><strong>{lowIsos}</strong></article><article><small>NEEDS ATTENTION</small><strong>{dashboard.alerts.length}</strong></article><article><small>ACTIVE WELLS</small><strong>{dashboard.activeWells.length}</strong></article></section><section className="grid"><AlertList dashboard={dashboard} /><ActiveWells dashboard={dashboard} /></section><TrailerTable dashboard={dashboard} /><InventoryTable dashboard={dashboard} /></> : <p className="empty">Choose a location to load live trailer and inventory data.</p>}</main></>;
}
